Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\programdata\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import joblib

clf = joblib.load('model.joblib')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m<ipython-input-1-4590f40dc350>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mimport[0m [0mjoblib[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;33m[0m[0m
[1;32m----> 3[1;33m [0mclf[0m [1;33m=[0m [0mjoblib[0m[1;33m.[0m[0mload[0m[1;33m([0m[1;34m'model.joblib'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32mC:\ProgramData\Anaconda3\lib\site-packages\joblib\numpy_pickle.py[0m in [0;36mload[1;34m(filename, mmap_mode)[0m
[0;32m    575[0m             [0mobj[0m [1;33m=[0m [0m_unpickle[0m[1;33m([0m[0mfobj[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    576[0m     [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 577[1;33m         [1;32mwith[0m [0mopen[0m[1;33m([0m[0mfilename[0m[1;33m,[0m [1;34m'rb'[0m[1;33m)[0m [1;32mas[0m [0mf[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    578[0m             [1;32mwith[0m [0m_read_fileobject[0m[1;33m([0m[0mf[0m[1;33m,[0m [0mfilename[0m[1;33m,[0m [0mmmap_mode[0m[1;33m)[0m [1;32mas[0m [0mfobj[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    579[0m                 [1;32mif[0m [0misinstance[0m[1;33m([0m[0mfobj[0m[1;33m,[0m [0mstr[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'model.joblib'
FileNotFoundError: [Errno 2] No such file or directory: 'model.joblib'

